#!/bin/sh
# Drift gate: the generated tree, the manifest and the bodies all agree with the sources.
set -u
# shellcheck disable=SC1091
. "$(dirname -- "$0")/00-lib.sh"

BODY="$ONB_ROOT/interview/BODY.md"
MANIFEST="$ONB_ROOT/generated/MANIFEST.json"
GENERATOR="$ONB_ROOT/tools/generate.py"
EXPECTED_HARNESSES="claude codex hermes opencode"

[ -f "$BODY" ] || skip_case "interview/BODY.md has not landed yet"
[ -f "$GENERATOR" ] || skip_case "tools/generate.py is missing"

if [ ! -f "$MANIFEST" ]; then
    fail_note "generated/MANIFEST.json is missing" "BODY.md exists, so the generated tree must exist too"
    finish
fi

VERSION=$(cat "$ONB_ROOT/VERSION" 2>/dev/null | tr -d ' \t\n')

# 1. the generator agrees with what is on disk
python3 "$GENERATOR" --check >"$ONB_TMP/check.out" 2>&1
assert_true $? "generate.py --check exits 0" "$(cat "$ONB_TMP/check.out")"

assert_eq "$EXPECTED_HARNESSES" "$(manifest_harnesses "$MANIFEST")" "manifest lists the four contract harnesses"
assert_eq "$VERSION" "$(manifest_top "$MANIFEST" version)" "manifest version matches VERSION"

BODY_SHA=$(sha256_of "$BODY")
assert_eq "$BODY_SHA" "$(manifest_top "$MANIFEST" body_sha256)" "manifest body_sha256 matches interview/BODY.md"

BODY_SIZE=$(file_size "$BODY")
FIRST=""

for harness in $EXPECTED_HARNESSES; do
    relpath=$(manifest_field "$MANIFEST" "$harness" generated_path)
    generated="$ONB_ROOT/$relpath"
    if [ ! -f "$generated" ]; then
        fail_note "$harness generated file is missing" "$generated"
        continue
    fi

    prefix_bytes=$(manifest_field "$MANIFEST" "$harness" prefix_bytes)

    # 3. content hash recorded in the manifest
    assert_eq "$(manifest_field "$MANIFEST" "$harness" sha256)" "$(sha256_of "$generated")" \
        "$harness generated sha256 matches the manifest"
    assert_eq "$BODY_SHA" "$(manifest_field "$MANIFEST" "$harness" body_sha256)" \
        "$harness manifest body_sha256 matches interview/BODY.md"

    # the generated file is exactly prefix plus an untouched body
    assert_eq "$((prefix_bytes + BODY_SIZE))" "$(file_size "$generated")" \
        "$harness file size is prefix_bytes plus the body size"

    head -c "$prefix_bytes" -- "$generated" >"$ONB_TMP/prefix.$harness"
    assert_eq "$(manifest_field "$MANIFEST" "$harness" prefix_sha256)" "$(sha256_of "$ONB_TMP/prefix.$harness")" \
        "$harness prefix sha256 matches the manifest"

    markers=$(grep -c '^<!-- generated by .*do not edit -->$' "$generated" || true)
    assert_eq "1" "$markers" "$harness carries exactly one generated marker line"
    marker_in_prefix=$(grep -c '^<!-- generated by .*do not edit -->$' "$ONB_TMP/prefix.$harness" || true)
    assert_eq "1" "$marker_in_prefix" "$harness generated marker sits in the prefix, not the body"
    if grep -q "^<!-- generated by .*interview/BODY\.md; cosift-onboarding v$VERSION; do not edit -->$" "$generated"; then
        pass_note "$harness marker names the source and version"
    else
        fail_note "$harness marker does not name interview/BODY.md and v$VERSION" \
            "$(grep '^<!-- generated by ' "$generated" || echo '(no marker line)')"
    fi

    # 2. the body survives verbatim
    tail -c "+$((prefix_bytes + 1))" -- "$generated" >"$ONB_TMP/body.$harness"
    assert_same_bytes "$ONB_TMP/body.$harness" "$BODY" "$harness body is byte-identical to interview/BODY.md"
    if [ -z "$FIRST" ]; then
        FIRST=$harness
    else
        assert_same_bytes "$ONB_TMP/body.$FIRST" "$ONB_TMP/body.$harness" \
            "$harness body is byte-identical to the $FIRST body"
    fi

    # 4. frontmatter key set is exactly the harness's allowed set
    profile="$ONB_ROOT/profiles/$harness.json"
    if [ ! -f "$profile" ]; then
        fail_note "$harness profile is missing" "$profile"
        continue
    fi
    assert_eq "$harness" "$(profile_keys_sorted "$profile" harness)" "$harness profile file names its own harness"

    emitted=$(frontmatter_keys "$generated" | tr '\n' ' ' | sed 's/ *$//')
    emitted_sorted=$(frontmatter_keys "$generated" | LC_ALL=C sort | tr '\n' ' ' | sed 's/ *$//')
    allowed=$(profile_keys_sorted "$profile" allowed_frontmatter_keys)
    assert_eq "$allowed" "$emitted_sorted" "$harness frontmatter key set equals its allowed set"
    assert_eq "$(manifest_field "$MANIFEST" "$harness" frontmatter_keys)" "$emitted" \
        "$harness frontmatter key order matches the manifest"
done

# codex accepts nothing but name and description, ever
CODEX_FILE="$ONB_ROOT/$(manifest_field "$MANIFEST" codex generated_path)"
if [ -f "$CODEX_FILE" ]; then
    codex_sorted=$(frontmatter_keys "$CODEX_FILE" | LC_ALL=C sort | tr '\n' ' ' | sed 's/ *$//')
    assert_eq "description name" "$codex_sorted" "codex frontmatter is ONLY name and description"
else
    fail_note "codex generated file is missing" "$CODEX_FILE"
fi

# the hermes wrapper carries its unverified banner and no other harness does
for harness in $EXPECTED_HARNESSES; do
    [ -f "$ONB_TMP/prefix.$harness" ] || continue
    banner=$(grep -c '^> ' "$ONB_TMP/prefix.$harness" || true)
    if [ "$harness" = hermes ]; then
        if [ "$banner" -gt 0 ]; then
            pass_note "hermes prefix carries banner lines"
        else
            fail_note "hermes prefix carries no banner lines"
        fi
        if grep -qi 'UNVERIFIED' "$ONB_TMP/prefix.hermes"; then
            pass_note "hermes banner says UNVERIFIED"
        else
            fail_note "hermes banner does not say UNVERIFIED"
        fi
        assert_eq "false" "$(manifest_field "$MANIFEST" hermes verified)" "manifest marks hermes unverified"
    else
        assert_eq "0" "$banner" "$harness prefix carries no banner"
    fi
done

finish
