#!/usr/bin/env python3
"""Write the onboarding payload into install.sh as quoted heredocs, or check it for drift."""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

BEGIN = "# >>> BEGIN EMBEDDED ONBOARDING PAYLOAD (generated by tools/embed-onboarding.py - do not edit)"
END = "# <<< END EMBEDDED ONBOARDING PAYLOAD"

BODY_EOF = "COSIFT_ONBOARDING_BODY_EOF"
PREFIX_EOF = "COSIFT_ONBOARDING_PREFIX_EOF"
BIN_EOF = "COSIFT_ONBOARDING_BIN_EOF"

SHIPPED = ("claude", "codex", "opencode")


class EmbedError(Exception):
    pass


def heredoc(payload: str, delimiter: str, indent: str = "") -> list[str]:
    # A quoted heredoc reproduces its content byte for byte, but it can only
    # represent newline-terminated text, and a content line equal to the
    # delimiter would end it early.  Only the `cat` line may be indented: the
    # body and the terminator have to stay at column 0.
    if not payload.endswith("\n"):
        raise EmbedError(f"payload for {delimiter} is not newline-terminated")
    for n, line in enumerate(payload.split("\n"), 1):
        if line == delimiter:
            raise EmbedError(f"payload for {delimiter} contains the delimiter at line {n}")
    return [f"{indent}cat <<'{delimiter}'", payload + delimiter]


def build_payload(root: Path) -> str:
    onb = root / "onboarding"
    manifest = json.loads((onb / "generated" / "MANIFEST.json").read_text(encoding="utf-8"))
    by_harness = {h["harness"]: h for h in manifest["harnesses"]}

    body = (onb / "interview" / "BODY.md").read_text(encoding="utf-8")
    command = (onb / "bin" / "cosift-onboarding").read_text(encoding="utf-8")

    out = [
        BEGIN,
        "#",
        "# The interview artifact, carried in the script so that `curl | sh` installs it with",
        "# no second fetch.  Rebuild with tools/embed-onboarding.py after any change under",
        "# onboarding/.  Composed per harness, these reproduce onboarding/generated/ byte for byte.",
        "",
        f"ONBOARDING_VERSION=\"{manifest['version']}\"",
        "",
        "onboarding_body() {",
    ]
    out += heredoc(body, BODY_EOF, "\t")
    out += ["}", "", "onboarding_prefix() {", '\tcase "$1" in']
    for harness in SHIPPED:
        entry = by_harness[harness]
        # prefix_bytes counts bytes, so the split happens before decoding.
        raw = (onb / entry["generated_path"]).read_bytes()
        prefix = raw[: entry["prefix_bytes"]].decode("utf-8")
        rest = raw[entry["prefix_bytes"] :].decode("utf-8")
        if rest != body:
            raise EmbedError(f"{entry['generated_path']} is not prefix + BODY.md")
        out.append(f"\t{harness})")
        out += heredoc(prefix, PREFIX_EOF, "\t\t")
        out.append("\t\t;;")
    out += ["\t*) return 1 ;;", "\tesac", "}", "", "onboarding_cmd_source() {"]
    out += heredoc(command, BIN_EOF, "\t")
    out += ["}", "", END]
    return "\n".join(out) + "\n"


def splice(script: str, payload: str) -> str:
    lines = script.split("\n")
    try:
        start = lines.index(BEGIN)
        stop = lines.index(END)
    except ValueError as exc:
        raise EmbedError(f"install.sh has no {BEGIN!r} / {END!r} block") from exc
    if stop < start:
        raise EmbedError("payload markers are in the wrong order")
    return "\n".join(lines[:start] + payload.rstrip("\n").split("\n") + lines[stop + 1 :])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 on drift, write nothing")
    ap.add_argument("--root", default=None, help="repository root (default: the script's parent)")
    args = ap.parse_args()

    root = Path(args.root) if args.root else Path(__file__).resolve().parent.parent
    script_path = root / "install.sh"

    try:
        current = script_path.read_text(encoding="utf-8")
        want = splice(current, build_payload(root))
    except EmbedError as exc:
        print(f"embed-onboarding: {exc}", file=sys.stderr)
        return 2

    if current == want:
        print("install.sh carries the current onboarding payload")
        return 0

    if args.check:
        diff = difflib.unified_diff(
            current.split("\n"), want.split("\n"), "install.sh", "expected", lineterm="", n=1
        )
        print("embed-onboarding: install.sh has drifted from onboarding/", file=sys.stderr)
        for n, line in enumerate(diff):
            if n > 40:
                print("  ...", file=sys.stderr)
                break
            print(f"  {line}", file=sys.stderr)
        return 1

    script_path.write_text(want, encoding="utf-8")
    print(f"install.sh payload rewritten ({len(want)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
